export const ActionsTypes = {
    GET_CITY_WEATHER : 'GET_CITY_WEATHER',
    ADD_TO_FAVORITES :'ADD_TO_FAVORITES',
    REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
    IS_LOADING: 'IS_LOADING',
    STOP_LOADING: 'STOP_LOADING'

};